CREATE TABLE deleted_channel (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id      CHAR(36) NOT NULL,
    name            VARCHAR2(255),
    user_id         NUMBER NOT NULL,
    date_deleted    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    content         CLOB
)

CREATE TABLE deleted_code_template (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_template_id    CHAR(36) NOT NULL,
    name                VARCHAR2(255),
    user_id             NUMBER NOT NULL,
    date_deleted        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    content             CLOB
)
